#ifndef __AtomicCoordinatesImportDialog__
#define __AtomicCoordinatesImportDialog__

/**
@file
Subclass of MovieImportDialog, which is generated by wxFormBuilder.
*/


//// end generated include

/** Implementing MovieImportDialog */
class AtomicCoordinatesImportDialog : public AtomicCoordinatesImportDialogParent
{
	public:
		/** Constructor */
		AtomicCoordinatesImportDialog( wxWindow* parent );
	//// end generated class members
	
		void AddFilesClick( wxCommandEvent& event );
		void ClearClick( wxCommandEvent& event );
		void CancelClick( wxCommandEvent& event );
		void AddDirectoryClick( wxCommandEvent& event );
		void ImportClick( wxCommandEvent& event );
		void OnTextKeyPress( wxKeyEvent& event );
		void CheckImportButtonStatus();
		void TextChanged( wxCommandEvent& event);
};


#endif // __MyMovieImportDialog__
