#ifndef __MovieAssetPanel__
#define __MovieAssetPanel__

/**
@file
Subclass of MovieAssetPanel, which is generated by wxFormBuilder.
*/

//// end generated include

// Drop target for drag and drop

class GroupDropTarget : public wxDropTarget
{

	private:

		wxListCtrl *my_owner;
		wxTextDataObject *my_data;

	public:
    	GroupDropTarget(wxListCtrl *owner);

    virtual bool OnDrop(wxCoord x, wxCoord y);//, const wxString& dropped_text);
    virtual wxDragResult OnData(wxCoord x, wxCoord y, wxDragResult defResult);
    virtual wxDragResult OnDragOver (wxCoord x, wxCoord y, wxDragResult defResult);
    virtual void OnLeave();
};


/** Implementing MovieAssetPanel */
class MyMovieAssetPanel : public MovieAssetPanel
{

		friend class GroupDropTarget;
	private:

		long selected_group;
		long selected_content;
		long highlighted_item;

		bool name_is_being_edited;

		AssetGroupList all_groups_list;
		MovieAssetList all_assets_list;

		void ImportMovieClick( wxCommandEvent& event );
		void RemoveMovieClick( wxCommandEvent& event );
		void RemoveAllClick( wxCommandEvent& event );
		void NewGroupClick( wxCommandEvent& event );
		void RemoveGroupClick( wxCommandEvent& event );
		void AddSelectedClick( wxCommandEvent& event );

	public:

		MyMovieAssetPanel( wxWindow* parent );

		void AddAsset(MovieAsset *asset_to_add);
		void AddContentItemToGroup(long wanted_group, long wanted_content_item);

		void OnGroupFocusChange( wxListEvent& event );
		void OnContentsSelected( wxListEvent& event );
		void OnBeginEdit( wxListEvent& event );
		void OnEndEdit( wxListEvent& event );
		void OnBeginContentsDrag( wxListEvent& event );

		void SizeGroupColumn();

		unsigned long ReturnNumberOfAssets();
		unsigned long ReturnNumberOfGroups();

		bool DragOverGroups(wxCoord x, wxCoord y);

		void SetGroupName(long wanted_group, wxString wanted_name);

		wxString ReturnGroupName(long wanted_group);
		wxString ReturnAssetShortFilename(long wanted_asset);
		wxString ReturnAssetLongFilename(long wanted_asset);

		long ReturnGroupSize(long wanted_group);
		long ReturnGroupMember(long wanted_group, long wanted_member);

		void CompletelyRemoveAsset(long wanted_asset);

		void FillGroupList();
		void FillContentsList();
		void UpdateMovieInfo();

		void SetSelectedGroup(long wanted_group);

		void CheckActiveButtons();

		bool IsFileAnAsset(wxFileName file_to_check);
};


#endif // __MovieAssetPanel__
