#ifndef __SRC_GUI__MyMovieImportDialog__
#define __SRC_GUI__MyMovieImportDialog__

/**
@file
Subclass of MovieImportDialog, which is generated by wxFormBuilder.
*/

//// end generated include

/** Implementing MovieImportDialog */
class MyMovieImportDialog : public MovieImportDialog {
  public:
    /** Constructor */
    MyMovieImportDialog(wxWindow* parent);
    //// end generated class members

    void AddFilesClick(wxCommandEvent& event);
    void ClearClick(wxCommandEvent& event);
    void CancelClick(wxCommandEvent& event);
    void AddDirectoryClick(wxCommandEvent& event);
    void ImportClick(wxCommandEvent& event);
    void OnTextKeyPress(wxKeyEvent& event);
    void CheckImportButtonStatus( );
    void TextChanged(wxCommandEvent& event);
    void CheckForEERFiles(wxArrayString& filenames, wxString& current_extension, bool& at_least_one_eer_file);

    void OnMoviesAreGainCorrectedCheckBox(wxCommandEvent& event);
    void OnCorrectMagDistortionCheckBox(wxCommandEvent& event);
    void OnGainFilePickerChanged(wxFileDirPickerEvent& event);
    void OnResampleMoviesCheckBox(wxCommandEvent& event);
    void OnSkipFullIntegrityCheckCheckBox(wxCommandEvent& event);

    const char* Type( ) const { return "ImportMovieDialog"; };
};

#endif // __MyMovieImportDialog__
