#ifndef __MyRefine3DPanel__
#define __MyRefine3DPanel__

/**
@file
Subclass of Refine3DPanel, which is generated by wxFormBuilder.
*/

#include "ProjectX_gui.h"

#define REFINEMENT 0
#define RECONSTRUCTION 1
#define MERGE 2

class MyRefine3DPanel;

class RefinementManager
{
public:
	bool start_with_reconstruction;
	MyRefine3DPanel *my_parent;

	long current_job_starttime;
	long time_of_last_update;
	int number_of_generated_3ds;

	int running_job_type;
	int number_of_rounds_to_run;
	int number_of_rounds_run;
	long current_job_id;

	long current_refinement_package_asset_id;
	long current_input_refinement_id;
	long current_output_refinement_id;

	long number_of_received_particle_results;

	Refinement *input_refinement;
	Refinement *output_refinement;

	void SetParent(MyRefine3DPanel *wanted_parent);

	void BeginRefinementCycle();
	void CycleRefinement();

	void SetupRefinementJob();
	void SetupReconstructionJob();
	void SetupMerge3dJob();

	void SetupInitialReconstructionJob();
	void SetupInitialMerge3dJob();

	void RunInitialReconstructionJob();
	void RunInitialMerge3dJob();

	void RunRefinementJob();
	void RunReconstructionJob();
	void RunMerge3dJob();

	void ProcessJobResult(JobResult *result_to_process);
	void ProcessAllJobsFinished();


//	void StartRefinement();
//	void StartReconstruction();


};


class MyRefine3DPanel : public Refine3DPanel
{
	friend class RefinementManager;

	protected:
		// Handlers for Refine3DPanel events.
		void OnUpdateUI( wxUpdateUIEvent& event );
		void OnExpertOptionsToggle( wxCommandEvent& event );
		void OnInfoURL( wxTextUrlEvent& event );
		void TerminateButtonClick( wxCommandEvent& event );
		void FinishButtonClick( wxCommandEvent& event );
		void StartRefinementClick( wxCommandEvent& event );
		void ResetAllDefaultsClick( wxCommandEvent& event );
		void OnHighResLimitChange( wxCommandEvent& event );

		void OnJobSocketEvent(wxSocketEvent& event);

		int length_of_process_number;



		RefinementManager my_refinement_manager;

	public:


		long time_of_last_result_update;
		bool refinement_package_combo_is_dirty;
		bool run_profiles_are_dirty;
		bool input_params_combo_is_dirty;

		JobResult *buffered_results;
		long my_job_id;
		long selected_refinement_package;

		//int length_of_process_number;

		JobPackage my_job_package;
		JobTracker my_job_tracker;

		bool running_job;

		void SetDefaults();


		MyRefine3DPanel( wxWindow* parent );
		void SetInfo();

		void WriteInfoText(wxString text_to_write);
		void WriteErrorText(wxString text_to_write);
		void WriteBlueText(wxString text_to_write);

		void FillRefinementPackagesComboBox();
		void FillRunProfileComboBoxes();
		void FillInputParamsComboBox();

		void NewRefinementPackageSelected();

		void OnRefinementPackageComboBox( wxCommandEvent& event );
		void OnInputParametersComboBox( wxCommandEvent& event );



};


#endif // __MyRefine3DPanel__
