#ifndef __MyRefine3DPanel__
#define __MyRefine3DPanel__

/**
@file
Subclass of Refine3DPanel, which is generated by wxFormBuilder.
*/

#include "ProjectX_gui.h"

class MyRefine3DPanel;

class RefinementManager
{
public:
	bool start_with_reconstruction;
	MyRefine3DPanel *my_parent;

	long current_job_starttime;
	long time_of_last_update;
	int number_of_generated_3ds;

	int running_job_type;
	int number_of_rounds_to_run;
	int number_of_rounds_run;
	long current_job_id;

	long current_refinement_package_asset_id;
	long current_input_refinement_id;
	long current_output_refinement_id;

	long number_of_received_particle_results;

	Refinement *input_refinement;
	Refinement *output_refinement;

	wxArrayString current_reference_filenames;

	void SetParent(MyRefine3DPanel *wanted_parent);

	void BeginRefinementCycle();
	void CycleRefinement();

	void SetupRefinementJob();
	void SetupReconstructionJob();
	void SetupMerge3dJob();

	void SetupInitialReconstructionJob();
	void SetupInitialMerge3dJob();

	void RunInitialReconstructionJob();
	void RunInitialMerge3dJob();

	void RunRefinementJob();
	void RunReconstructionJob();
	void RunMerge3dJob();

	void ProcessJobResult(JobResult *result_to_process);
	void ProcessAllJobsFinished();

	void OnMaskerThreadComplete();

	void DoMasking();

//	void StartRefinement();
//	void StartReconstruction();


};


class MyRefine3DPanel : public Refine3DPanel
{
	friend class RefinementManager;

	protected:
		// Handlers for Refine3DPanel events.
		void OnUpdateUI( wxUpdateUIEvent& event );
		void OnExpertOptionsToggle( wxCommandEvent& event );
		void OnInfoURL( wxTextUrlEvent& event );
		void TerminateButtonClick( wxCommandEvent& event );
		void FinishButtonClick( wxCommandEvent& event );
		void StartRefinementClick( wxCommandEvent& event );
		void ResetAllDefaultsClick( wxCommandEvent& event );
		void OnHighResLimitChange( wxCommandEvent& event );
		void OnUseMaskCheckBox( wxCommandEvent& event );
		void OnVolumeListItemActivated( wxListEvent& event );
		void OnJobSocketEvent(wxSocketEvent& event);

		int length_of_process_number;



		RefinementManager my_refinement_manager;

	public:


		long time_of_last_result_update;

		bool refinement_package_combo_is_dirty;
		bool run_profiles_are_dirty;
		bool input_params_combo_is_dirty;
		bool volumes_are_dirty;

		JobResult *buffered_results;
		long my_job_id;
		long selected_refinement_package;

		//int length_of_process_number;

		JobPackage my_job_package;
		JobTracker my_job_tracker;

		bool running_job;

		void SetDefaults();


		MyRefine3DPanel( wxWindow* parent );
		void SetInfo();

		void WriteInfoText(wxString text_to_write);
		void WriteErrorText(wxString text_to_write);
		void WriteBlueText(wxString text_to_write);

		void FillRefinementPackagesComboBox();
		void FillRunProfileComboBoxes();
		void FillInputParamsComboBox();
		void ReDrawActiveReferences();

		void NewRefinementPackageSelected();

		void OnRefinementPackageComboBox( wxCommandEvent& event );
		void OnInputParametersComboBox( wxCommandEvent& event );

		void OnOrthThreadComplete(MyOrthDrawEvent& my_event);
		void OnMaskerThreadComplete(wxThreadEvent& my_event);
};

class Refine3DMaskerThread : public wxThread
{
	public:
	Refine3DMaskerThread(Refine3DPanel *parent, wxArrayString wanted_input_files, wxArrayString wanted_output_files, wxString wanted_mask_filename, float wanted_cosine_edge_width, float wanted_weight_outside_mask, float wanted_low_pass_filter_radius, float wanted_filter_cosine_edge_width) : wxThread(wxTHREAD_DETACHED)
	{
		main_thread_pointer = parent;
		input_files = wanted_input_files;
		output_files = wanted_output_files;
		mask_filename = wanted_mask_filename;
		cosine_edge_width = wanted_cosine_edge_width;
		weight_outside_mask = wanted_weight_outside_mask;
		low_pass_filter_radius = wanted_low_pass_filter_radius;
		filter_cosine_edge_width = wanted_filter_cosine_edge_width;
	}

	protected:

	Refine3DPanel *main_thread_pointer;
	wxArrayString input_files;
	wxArrayString output_files;
	wxString mask_filename;

	float cosine_edge_width;
	float weight_outside_mask;
	float low_pass_filter_radius;
	float filter_cosine_edge_width;

    virtual ExitCode Entry();
};


#endif // __MyRefine3DPanel__
