#include "blush_logger.h"
#include "blush_helpers.h"
#include "block_iterator.h"

#include <chrono>
#include <fstream>
#include <iostream>
#include <unistd.h>
#include <cstdio>

namespace BlushHelpers {
torch::Tensor get_local_std_dev(torch::Tensor grid, int size) {
    // Unsqueeze and clone the grid tensor
    torch::Tensor new_grid = grid.unsqueeze(1).clone( );
    torch::Tensor grid2    = new_grid.square( );

    // Create the kernel
    torch::Tensor ls     = torch::linspace(-1.5, 1.5, 2 * size + 1); // Create tensor of size 2 * size + 1 with evenly spaced values between -1.5 and 1.5 -- size passed as 10
    torch::Tensor kernel = torch::exp(-ls.square( )).to(new_grid.device( )); // Make normal dist (gets rid of negatives (square), applies exponential function(exp))
    kernel /= kernel.sum( );

    kernel = kernel.unsqueeze(0).unsqueeze(0).unsqueeze(3).unsqueeze(4); // Shape: (1, 1, kernel_size, 1, 1)

    // Set options, then perform 3D convolution
    torch::nn::functional::Conv3dFuncOptions options;

    // Pads tensors by size in either direction of x, y, and z dimensions (if size == 10, then padding totals 20)
    new_grid = torch::constant_pad_nd(new_grid, {size, size, size, size, size, size});
    grid2    = torch::constant_pad_nd(grid2, {size, size, size, size, size, size});

    // This convolution will remove the padded dimensions
    for ( int i = 0; i < 3; ++i ) {
        new_grid = new_grid.permute({0, 1, 4, 2, 3}).contiguous( ); // Shift (N, C, D, W, H) then (N, C, H, D, W) and finally (N, C, W, H, D)
        new_grid = torch::nn::functional::conv3d(new_grid, kernel, options);

        grid2 = grid2.permute({0, 1, 4, 2, 3}).contiguous( ); // Same permutation
        grid2 = torch::nn::functional::conv3d(grid2, /*weight=*/kernel, options);
    }

    torch::Tensor in_std = torch::sqrt(torch::clamp(grid2 - new_grid.square( ), 0));
    in_std               = in_std.squeeze(0);

    return in_std.clone( );
}

/**
 * @brief Generate a 3D grid of weights where each dimension is of size block_size.
 * 
 * @param block_size The size of segments passed to the model -- comes from model's previously set model_block_size.
 * @param margin The thickness of the border around the distribution generated by 
 * @return Tensor 
 */
torch::Tensor make_weight_box(const int& block_size, int margin) {
    margin = (margin - 1 > 0) ? margin - 1 : 0;
    int s  = block_size - (margin * 2);

    // Create evenly spaced 1D tensors; should range from -27 to 27, with increments of...55?
    torch::Tensor x = torch::linspace(-s / 2, s / 2, s);
    torch::Tensor y = torch::linspace(-s / 2, s / 2, s);
    torch::Tensor z = torch::linspace(-s / 2, s / 2, s);

    // Broadcasting means these tensors can be subsequently expanded to fit the appropriate dimensions as needed
    // Each of these tensors is different, and later they are sliced together dimensionally
    // expand broadcasts the dimension with s, so the values of the linspace array are applied in all 3 dimensions
    // This is meant to replicate numpy.meshgrid functionality
    torch::Tensor xx = x.view({s, 1, 1}).expand({s, s, s});
    torch::Tensor yy = y.view({1, s, 1}).expand({s, s, s});
    torch::Tensor zz = z.view({1, 1, s}).expand({s, s, s});

    // Radial distance: elementwise max of the three absolute-coordinate tensors.
    // NOTE: torch::max(Tensor, Tensor) is the elementwise overload and returns a plain Tensor;
    // only the reduction overload torch::max(Tensor, dim) returns a (values, indices) tuple.
    xx                   = xx.abs( );
    yy                   = yy.abs( );
    zz                   = zz.abs( );
    torch::Tensor radius = torch::max(torch::max(xx, yy), zz);

    radius = torch::cos(radius / radius.max( ) * (M_PI / 2));

    // Sets up the output tensor that will slice from each of the tensors
    torch::Tensor weight_grid = torch::zeros({block_size, block_size, block_size});
    auto          slices      = weight_grid.slice(0, margin, block_size - margin).slice(1, margin, block_size - margin).slice(2, margin, block_size - margin);
    slices.copy_(radius);
    weight_grid = weight_grid.clamp_min(1e-6); // avoid zeros

    return weight_grid;
}

/**
 * @brief Generate what is essentially a cosine mask using torch functions for faster subsequent application
 * to a tensorized volume.
 * 
 * @param box_size Outer dimension of the mask (same as volume).
 * @param radius Size of outer edge of the mask in pixels.
 * @param mask_edge_width How wide in pixels the falloff edge of the mask should be.
 * @return torch::Tensor A 3D mask volume in tensor form.
 */
torch::Tensor generate_radial_mask(const int& box_size, const float& radius, const int& mask_edge_width) {
    float         bz2 = box_size / 2.0f;
    torch::Tensor ls  = torch::linspace(-bz2, bz2, box_size);
    torch::Tensor r   = torch::stack(torch::meshgrid({ls, ls, ls}), -1);

    r = torch::sqrt(torch::sum(torch::square(r), -1));

    torch::Tensor scale = torch::ones_like(r);

    if ( mask_edge_width > 0 ) {
        int edge_low  = radius - mask_edge_width / 2;
        int edge_high = radius + mask_edge_width / 2;

        // torch::where is a boolean mask function
        torch::Tensor mask = (r >= edge_low) & (r <= edge_high);
        scale              = torch::where(r > edge_high, 0, scale);
        // scale              = torch::where(mask, 0.5 + 0.5 * torch::cos(M_PI * (torch::where((r >= edge_low) & (r <= edge_high), r - edge_low, r)) / mask_edge_width), scale);
        scale = torch::where(mask, 0.5 + 0.5 * torch::cos(M_PI * (r - edge_low) / mask_edge_width), scale);
    }
    else {
        scale = torch::where(r > radius, 0, scale);
    }

    // write_real_values_to_text_file("cpp_radial_mask_writeout.txt", box_size, false, true, &scale);
    // compare_text_file_lines("cpp_radial_mask_writeout.txt", "py_radial_mask_writeout.txt", "comp_radial_mask_writeout.txt");

    return scale;
}

/**
 * @brief Uses Blush regularization model for inference of the input_volume passed during 3D refinement. As of now, it is only called by the masking threads AutoMaskerThread
 * and Multiply3DMasker thread in my_controls.cpp, prior to the application of the automask or custom mask.
 * 
 * @param input_volume Volume to have inference applied.
 * @param pixel_size Pixel size of the volume, needed for adjusting sampling to the voxel size used by the Blush model.
 * @param mask_radius Radius of the user defined mask.
 * @param batch_size Number of blocks passed to the blush model per forward pass.
 * @param max_threads Maximum number of allowed threads LibTorch is allowed.
 * @param stop_flag Used for transmission of user interrupt from the GUI to halt function execution.
 * @param progress_callback Updates the main GUI thread progress bar to prevent unmoving GUI.
 */
void ApplyBlush(std::vector<float>& input_volume, const std::string& model_filename, const int& box_size, const float& mask_radius, const int& batch_size, const int& max_threads, std::shared_ptr<std::atomic<bool>> stop_flag, std::function<bool(int percentage, long seconds_remaining)> progress_callback) {

    // NOTE: this is a no_grad guard, so that the Blush model does not track gradients in a computation graph for the forward pass.
    // If it were to track gradients, it would consume a lot of memory (sometimes greater than 32 GB).
    // These computation graphs are used for backpropagation during neural network training, which is not needed in this case as this
    // is using the model in inference mode (i.e., for making predictions rather than training), along with loaded weights.
    // torch::NoGradGuard no_grad;

    torch::set_num_threads(max_threads);
    // torch::set_num_interop_threads(1);

    constexpr float model_voxel_size{1.5f}; // The expected voxel/pixel size of inputs to the blush model
    constexpr int   model_block_size{64};
    constexpr int   strides{20};
    constexpr int   in_channels{2};

    BlushModel model(2, 2);
    try {
        model.load_weights(model_filename);
    } catch ( std::exception& e ) {
        BLUSH_LOG_ERROR("Error loading model weights: %s. Try copying blush_weights.dat to cisTEM binary directory.", e.what( ));
        return;
    }

    model.eval( );

    torch::Tensor                 blocks;
    std::vector<std::vector<int>> coords;
    torch::Tensor                 volume_tensor;
    torch::Tensor                 local_std_dev;
    torch::Tensor                 weights;
    torch::Tensor                 infer_grid;
    torch::Tensor                 count_grid;
    torch::Tensor                 mask_tensor;

    // Set up tensors to be used for model and model setup
    try {
        blocks        = torch::zeros({batch_size, in_channels, model_block_size, model_block_size, model_block_size});
        coords        = std::vector(batch_size, std::vector<int>(3, 0));
        volume_tensor = torch::zeros({box_size, box_size, box_size}, torch::kFloat32);
        local_std_dev = torch::zeros({box_size, box_size, box_size}, torch::kFloat32);
    } catch ( std::exception& e ) {
        BLUSH_LOG_ERROR("Error setting up tensors: %s", e.what( ));
        return;
    }

    // input_volume.RemoveFFTWPadding( );

    volume_tensor = torch::from_blob(input_volume.data( ), {box_size, box_size, box_size}, torch::kFloat32).clone( ).contiguous( );
    volume_tensor = volume_tensor.permute({2, 1, 0}).contiguous( ); // Change to (z, y, x) order for LibTorch

    weights    = make_weight_box(model_block_size, 10);
    infer_grid = torch::zeros({box_size, box_size, box_size}, torch::kFloat32);
    count_grid = torch::zeros({box_size, box_size, box_size}, torch::kFloat32);

    float volume_mean{0.0f}, volume_std{1.0f};
    try {
        torch::Tensor tmp_volume_clone   = volume_tensor.clone( ).contiguous( );
        torch::Tensor tmp_local_std_dev  = get_local_std_dev(tmp_volume_clone.unsqueeze(0), 10).squeeze(0).contiguous( ).clone( );
        torch::Tensor local_std_dev_mean = tmp_local_std_dev.mean( );
        volume_mean                      = volume_tensor.mean( ).item<float>( );
        volume_std                       = volume_tensor.std( ).item<float>( );

        local_std_dev = tmp_local_std_dev / local_std_dev_mean;
        volume_tensor = (volume_tensor - volume_mean) / (volume_std + 1e-8);
    } catch ( std::exception& e ) {
        BLUSH_LOG_ERROR("Error getting localized standard deviation and normalizing volume tensor: %s", e.what( ));
        return;
    }

    // Generate the mask
    int mask_edge_width = static_cast<int>(20.0f / model_voxel_size);
    mask_tensor         = generate_radial_mask(box_size, mask_radius, mask_edge_width);

    // input_3d.mask_radius = mask_radius;
    volume_tensor *= mask_tensor;
    local_std_dev *= mask_tensor;

    // Set up done, now pass to the model
    int bi = 0;
    try {
        BlockIterator it({box_size, box_size, box_size}, model_block_size, strides);
        // int           bi = 0;
        //////////////// FOR UPDATING GUI /////////////////////////////////////////////////////
        // bool                                  calculated_avg_duration{false};
        std::chrono::system_clock::time_point global_start_time{std::chrono::high_resolution_clock::now( )};
        int                                   current_iteration{0};
        int                                   last_percent{-1};
        int                                   total_iterations{it.begin( ).size( )};
        int                                   percent_completion{0};
        ///////////////////////////////////////////////////////////////////////////////////////

        std::vector<std::tuple<int, int, int>> batch_coords;
        batch_coords.reserve(batch_size);

        double forward_only_ms{0.0};
        long   forward_call_count{0};

        for ( auto it_coords : it ) {
            /* This is an InferenceMode guard that prevents the BlushModel using LibTorch from tracking
			   unnecessary data while processing, such as gradients, which are used for training. If
			   this were tracked it could result in using excessive amounts of memory.
			*/

            torch::InferenceMode inference;
            if ( stop_flag && stop_flag->load(std::memory_order_relaxed) ) {
                return;
            }

            torch::Tensor volume_block;
            torch::Tensor std_dev_block;

            // auto it_coords = it.get_coords_by_index(i);
            int x = std::get<0>(it_coords);
            int y = std::get<1>(it_coords);
            int z = std::get<2>(it_coords);

            current_iteration++;
            // Here -1 is just a method for determining if iterations have finished; could probably improve clarity,
            // but for now this note is enough.
            if ( x > -1 ) {
                torch::Tensor current_slice = mask_tensor.slice(0, z, z + model_block_size).slice(1, y, y + model_block_size).slice(2, x, x + model_block_size);
                float         mask_mean     = current_slice.mean( ).item<float>( );

                // Skip this block if the mask mean is quite low as there must not be much density here.

                // Using blush mask and the mean is too small
                constexpr float mean_threshold = 0.3f;
                if ( mask_mean < mean_threshold ) {
                    continue;
                }

                volume_block  = volume_tensor.slice(0, z, z + model_block_size).slice(1, y, y + model_block_size).slice(2, x, x + model_block_size);
                std_dev_block = local_std_dev.slice(0, z, z + model_block_size).slice(1, y, y + model_block_size).slice(2, x, x + model_block_size);

                blocks.select(0, bi).select(0, 0).copy_(volume_block);
                blocks.select(0, bi).select(0, 1).copy_(std_dev_block);

                batch_coords.push_back({x, y, z});
                bi++;

                if ( bi == batch_size ) {
                    // Returns inference results and a mask (all that's relevant here is the inference results)
                    torch::Tensor                            batch         = blocks.slice(0, 0, bi);
                    auto                                     forward_start = std::chrono::high_resolution_clock::now( );
                    std::tuple<torch::Tensor, torch::Tensor> output        = model.forward(batch.select(1, 0).contiguous( ), batch.select(1, 1).contiguous( ));
                    forward_only_ms += std::chrono::duration<double, std::milli>(std::chrono::high_resolution_clock::now( ) - forward_start).count( );
                    forward_call_count++;

                    // Extracts batches
                    torch::Tensor vol_outputs = std::get<0>(output).clone( );

                    for ( int i = 0; i < bi; i++ ) {
                        int bx = std::get<0>(batch_coords[i]);
                        int by = std::get<1>(batch_coords[i]);
                        int bz = std::get<2>(batch_coords[i]);

                        torch::Tensor vol_out_single = vol_outputs.select(0, i) * weights;
                        infer_grid.slice(0, bz, bz + model_block_size).slice(1, by, by + model_block_size).slice(2, bx, bx + model_block_size) += vol_out_single;
                        count_grid.slice(0, bz, bz + model_block_size).slice(1, by, by + model_block_size).slice(2, bx, bx + model_block_size) += weights;
                    }

                    bi = 0;
                    batch_coords.clear( );
                }
            }

            // Send a scope-controlled update of progress to the GUI
            {
                percent_completion = (float(current_iteration) / total_iterations) * 100;
                percent_completion = std::min(percent_completion, 100);
                if ( percent_completion - last_percent >= 5 && percent_completion != last_percent ) {
                    int percent_increment       = percent_completion - last_percent;
                    last_percent                = percent_completion;
                    auto   now                  = std::chrono::high_resolution_clock::now( );
                    double seconds_elapsed      = std::chrono::duration<double>(now - global_start_time).count( );
                    double seconds_per_iter     = seconds_elapsed / double(current_iteration);
                    long   iterations_remaining = total_iterations - current_iteration;
                    long   seconds_remaining    = static_cast<long>(seconds_per_iter * iterations_remaining);

                    if ( ! progress_callback(percent_increment, seconds_remaining) ) {
                        return;
                    }
                }
            }
        }

        // Finally, if total valid blocks isn't a perfect multiple of batch_size, process what remains
        if ( bi > 0 ) {
            torch::Tensor                            batch         = blocks.slice(0, 0, bi);
            auto                                     forward_start = std::chrono::high_resolution_clock::now( );
            std::tuple<torch::Tensor, torch::Tensor> output        = model.forward(batch.select(1, 0).contiguous( ), batch.select(1, 1).contiguous( ));
            forward_only_ms += std::chrono::duration<double, std::milli>(std::chrono::high_resolution_clock::now( ) - forward_start).count( );
            forward_call_count++;
            // torch::Tensor vol_outputs    = std::get<0>(initial_output).clone( );
            torch::Tensor vol_outputs = std::get<0>(output).clone( );

            for ( int i = 0; i < bi; i++ ) {
                int bx = std::get<0>(batch_coords[i]);
                int by = std::get<1>(batch_coords[i]);
                int bz = std::get<2>(batch_coords[i]);

                torch::Tensor vol_out_single = vol_outputs.select(0, i) * weights;

                infer_grid.slice(0, bz, bz + model_block_size, 1).slice(1, by, by + model_block_size, 1).slice(2, bx, bx + model_block_size, 1) += vol_out_single;
                count_grid.slice(0, bz, bz + model_block_size, 1).slice(1, by, by + model_block_size, 1).slice(2, bx, bx + model_block_size, 1) += weights;
            }
        }

#ifdef BLUSH_DEBUG_LOGGING
        BLUSH_LOG_INFO("[PROFILE] Block loop (%d blocks): %.1f ms", total_iterations, std::chrono::duration<double, std::milli>(std::chrono::high_resolution_clock::now( ) - global_start_time).count( ));
        BLUSH_LOG_INFO("[PROFILE] forward() total: %.1f ms across %ld calls (avg %.2f ms/call)", forward_only_ms, forward_call_count, forward_call_count > 0 ? forward_only_ms / forward_call_count : 0.0);
#endif

        infer_grid = torch::where(count_grid > 0, infer_grid / count_grid, infer_grid);
        infer_grid = torch::where(count_grid < 1e-1f, torch::full_like(infer_grid, 0.0f), infer_grid); // Set values where count_grid is less than 0.1 to 0
        infer_grid *= mask_tensor;

        infer_grid = infer_grid * (volume_std + 1e-8) + volume_mean; // Normalize the inference grid

        if ( (stop_flag && stop_flag->load(std::memory_order_relaxed)) || ! progress_callback(100 - percent_completion, 0) )
            return;

        // Finally, put the result back into the input_3d.density_map, and handle resampling if needed
        infer_grid *= mask_tensor;

        infer_grid = infer_grid.permute({2, 1, 0}).contiguous( ); // Change back to (x, y, z) order for MRC output
        std::memcpy(input_volume.data( ), infer_grid.data_ptr<float>( ), sizeof(float) * std::pow(box_size, 3));
    } catch ( std::exception& e ) {
        BLUSH_LOG_ERROR("Error running Blush inference: block processing failed: %s", e.what( ));
        return;
    }
}
} // namespace BlushHelpers