name: cisTEM cpu debug

on:
  workflow_run:
    workflows: ["Check C++ Formatting"]
    types:
      - completed
    branches:
      - master
      - '*_with_ci'
  pull_request:
    branches:
      - master
      - '*_with_ci'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_build:
    if: ${{ github.event_name == 'pull_request' || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/run_builds.yml
    with:
      build_type: "cpu_debug"
      configure_options: "--enable-debugmode "
      global_configure_options: " --disable-FastFFT --enable-openmp --enable-experimental --disable-multiple-global-refinements  --disable-multiple-global-refinements --with-wx-config=/opt/WX/icc-static/bin/wx-config"
      runs_on_os: ubuntu-latest
      CC: icc
      CXX: icpc
      cppstandard: 17
      run_tests: true
      n_threads: 4
