name: cisTEM GPU release

on:
  push:
    branches:
      - master
      - '*_with_ci'
  pull_request:
    branches: master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_build:
    uses: ./.github/workflows/run_builds.yml
    with:
      build_type: "GPU_release"
      configure_options: "--with-cuda "
      global_configure_options: " --enable-openmp --enable-experimental --disable-multiple-global-refinements  --with-wx-config=/opt/WX/icc-static/bin/wx-config "
      runs_on_os: ubuntu-latest
      CC: icc
      CXX: icpc
      cppstandard: 17
      run_tests: false
      n_threads: 4
