name: cisTEM GPU release, GNU MKL

on:
  workflow_run:
    workflows: ["Check C++ Formatting"]
    types:
      - completed
    branches:
      - master
      - '*_with_ci'
  pull_request:
    branches:
      - master
      - '*_with_ci'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_build:
    if: ${{ github.event_name == 'pull_request' || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/run_builds.yml
    with:
      build_type: "GPU_release_GNU_MKL"
      configure_options: "--with-cuda "
      global_configure_options: "  --disable-FastFFT --enable-openmp --enable-experimental --with-wx-config=/opt/WX/gcc-static/bin/wx-config --disable-multiple-global-refinements  "
      runs_on_os: ubuntu-latest
      CC: gcc
      CXX: g++
      cppstandard: 17
      run_tests: false
      n_threads: 4
