name: cisTEM GPU release no experimental full build

on:
  workflow_call:

jobs:
  run_build:
    uses: ./.github/workflows/run_builds.yml
    with:
      build_type: "GPU_release_no_experimental_full"
      configure_options: "--with-cuda "
      global_configure_options: "  --disable-FastFFT --enable-openmp --disable-multiple-global-refinements  --with-wx-config=/opt/WX/icc-static/bin/wx-config"
      runs_on_os: ubuntu-latest
      CC: icc
      CXX: icpc
      cppstandard: 17
      run_tests: false
      n_threads: 4
