name: cisTEM GPU release, clang MKL

on:
  push:
    branches:
      - master
      - '*_with_ci'
  pull_request:
    branches: master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_build:
    uses: ./.github/workflows/run_builds.yml
    with:
      build_type: "GPU_release_clang_MKL"
      configure_options: "--with-cuda "
      global_configure_options: "  --disable-FastFFT --enable-openmp --enable-experimental --with-wx-config=/opt/WX/clang-static/bin/wx-config --disable-multiple-global-refinements  "
      runs_on_os: ubuntu-latest
      CC: clang
      CXX: clang++
      cppstandard: 17
      run_tests: false
      n_threads: 4
